// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTeamXP.Data;

#nullable disable

namespace ProyectoTeamXP.Migrations
{
    [DbContext(typeof(TeamXPDbContext))]
    partial class TeamXPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoTeamXP.Models.ArchivoProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminado");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaSubida");

                    b.Property<string>("NombreOriginal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreOriginal");

                    b.Property<string>("RutaServidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RutaServidor");

                    b.Property<string>("TipoArchivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoArchivo");

                    b.Property<string>("TipoVista")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoVista");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ArchivosProgreso");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ClienteMacros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calorias")
                        .HasColumnType("int")
                        .HasColumnName("Calorias");

                    b.Property<decimal?>("Carbohidratos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Carbohidratos");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<decimal?>("Grasa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Grasa");

                    b.Property<decimal?>("Proteina")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Proteina");

                    b.Property<string>("TipoDia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoDia");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClienteMacros");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ClientePerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("Edad");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<DateTime?>("FechaInicioPrograma")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInicioPrograma");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaModificacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("ObjetivoCardio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ObjetivoCardio");

                    b.Property<string>("ObjetivoPasos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ObjetivoPasos");

                    b.Property<string>("Objetivos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Objetivos");

                    b.Property<decimal?>("PesoInicial")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PesoInicial");

                    b.Property<string>("Suplementacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Suplementacion");

                    b.Property<bool>("TerminosAceptados")
                        .HasColumnType("bit")
                        .HasColumnName("TerminosAceptados");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioEliminacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioModificacion");

                    b.Property<int>("UsuarioSeguridadId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioSeguridadId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioSeguridadId")
                        .IsUnique();

                    b.ToTable("ClientesPerfil");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.MedidaCorporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Brazo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Brazo");

                    b.Property<decimal?>("Cadera")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Cadera");

                    b.Property<decimal?>("CinturaBajoOmbligo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CinturaBajoOmbligo");

                    b.Property<decimal?>("CinturaOmbligo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CinturaOmbligo");

                    b.Property<decimal?>("CinturaSobreOmbligo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CinturaSobreOmbligo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<decimal?>("Muslos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Muslos");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSemana");

                    b.Property<decimal?>("Pecho")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Pecho");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("MedidasCorporales");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.NotasSemanalesCoach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("Anio");

                    b.Property<string>("CambiosAlteraciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CambiosAlteraciones");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("NotasCardio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotasCardio");

                    b.Property<string>("NotasEntrenamiento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotasEntrenamiento");

                    b.Property<string>("NotasNutricion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotasNutricion");

                    b.Property<int>("SemanaNumero")
                        .HasColumnType("int")
                        .HasColumnName("SemanaNumero");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("NotasSemanalesCoach");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.PlanNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Alimento");

                    b.Property<string>("Cantidad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cantidad");

                    b.Property<string>("CantidadSustituto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CantidadSustituto");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Comida")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comida");

                    b.Property<int?>("OrdenComida")
                        .HasColumnType("int")
                        .HasColumnName("OrdenComida");

                    b.Property<string>("Sustituto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sustituto");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("PlanNutricional");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ProgresionSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("CargaKg");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comentarios");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSemana");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSerie");

                    b.Property<int?>("RIRRealizado")
                        .HasColumnType("int")
                        .HasColumnName("RIRRealizado");

                    b.Property<int?>("RepsRealizadas")
                        .HasColumnType("int")
                        .HasColumnName("RepsRealizadas");

                    b.Property<int>("RutinaEjercicioId")
                        .HasColumnType("int")
                        .HasColumnName("RutinaEjercicioId");

                    b.HasKey("Id");

                    b.HasIndex("RutinaEjercicioId");

                    b.ToTable("ProgresionSeries");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RecursoFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Titulo");

                    b.Property<string>("UrlVideo1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlVideo1");

                    b.Property<string>("UrlVideo2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlVideo2");

                    b.HasKey("Id");

                    b.ToTable("RecursosFAQ");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RevisionFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<string>("ExitosSemana")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExitosSemana");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCompletado");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRevision");

                    b.Property<string>("FeedbackAnimo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackAnimo");

                    b.Property<string>("FeedbackApoyo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackApoyo");

                    b.Property<string>("FeedbackEntreno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackEntreno");

                    b.Property<string>("FeedbackFisico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackFisico");

                    b.Property<string>("FeedbackNutricion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FeedbackNutricion");

                    b.Property<string>("ProximasSemanas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProximasSemanas");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("RevisionesFeedback");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RutinaEjercicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("DiaRutina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaRutina");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminado");

                    b.Property<string>("EsfuerzoObjetivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EsfuerzoObjetivo");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<string>("GrupoMuscular")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GrupoMuscular");

                    b.Property<string>("LinkVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkVideo");

                    b.Property<string>("NombreEjercicio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreEjercicio");

                    b.Property<string>("NotasTecnicas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NotasTecnicas");

                    b.Property<int?>("OrdenEjercicio")
                        .HasColumnType("int")
                        .HasColumnName("OrdenEjercicio");

                    b.Property<string>("RepsRango")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RepsRango");

                    b.Property<int?>("SeriesObjetivo")
                        .HasColumnType("int")
                        .HasColumnName("SeriesObjetivo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.SeguimientoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apetito")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apetito");

                    b.Property<string>("CalidadSueno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CalidadSueno");

                    b.Property<decimal?>("Carbohidratos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Carbohidratos");

                    b.Property<bool>("CardioRealizado")
                        .HasColumnType("bit")
                        .HasColumnName("CardioRealizado");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("DiaEntreno")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaEntreno");

                    b.Property<string>("DuracionCardio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuracionCardio");

                    b.Property<bool>("EntrenoRealizado")
                        .HasColumnType("bit")
                        .HasColumnName("EntrenoRealizado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<decimal?>("Grasa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Grasa");

                    b.Property<TimeSpan?>("HoraPesaje")
                        .HasColumnType("time")
                        .HasColumnName("HoraPesaje");

                    b.Property<decimal?>("HorasSueno")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("HorasSueno");

                    b.Property<string>("NivelEstres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NivelEstres");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notas");

                    b.Property<int?>("NumeroSemana")
                        .HasColumnType("int")
                        .HasColumnName("NumeroSemana");

                    b.Property<int?>("PasosRealizados")
                        .HasColumnType("int")
                        .HasColumnName("PasosRealizados");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Peso");

                    b.Property<decimal?>("Proteina")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Proteina");

                    b.Property<string>("RendimientoSesion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RendimientoSesion");

                    b.Property<int?>("TotalCalorias")
                        .HasColumnType("int")
                        .HasColumnName("TotalCalorias");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("SeguimientoDiario");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.UsuarioSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit")
                        .HasColumnName("Eliminado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEliminacion");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PasswordPlain_SOLO_TESTING")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordPlain_SOLO_TESTING");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolId");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.Property<string>("UsuarioEliminacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UsuarioEliminacion");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("UsuariosSeguridad");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ArchivoProgreso", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("Archivos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ClienteMacros", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("Macros")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ClientePerfil", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.UsuarioSeguridad", "UsuarioSeguridad")
                        .WithOne("ClientePerfil")
                        .HasForeignKey("ProyectoTeamXP.Models.ClientePerfil", "UsuarioSeguridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioSeguridad");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.MedidaCorporal", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.NotasSemanalesCoach", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("NotasSemanales")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.PlanNutricional", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("PlanNutricional")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ProgresionSeries", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.RutinaEjercicios", "RutinaEjercicio")
                        .WithMany("ProgresionSeries")
                        .HasForeignKey("RutinaEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaEjercicio");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RevisionFeedback", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("Revisiones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RutinaEjercicios", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.SeguimientoDiario", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.ClientePerfil", "Cliente")
                        .WithMany("SeguimientoDiario")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.UsuarioSeguridad", b =>
                {
                    b.HasOne("ProyectoTeamXP.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.ClientePerfil", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Macros");

                    b.Navigation("NotasSemanales");

                    b.Navigation("PlanNutricional");

                    b.Navigation("Revisiones");

                    b.Navigation("RutinaEjercicios");

                    b.Navigation("SeguimientoDiario");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.RutinaEjercicios", b =>
                {
                    b.Navigation("ProgresionSeries");
                });

            modelBuilder.Entity("ProyectoTeamXP.Models.UsuarioSeguridad", b =>
                {
                    b.Navigation("ClientePerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
